# Generated by install-client-windows.ps1 - do not edit manually
# The log goes to %LOCALAPPDATA%\magnetgate, never into the repository: a tunnel client's log is a
# record of everything the user visited, so it must not sit in a folder that can be committed, zipped
# or shared with the code.
$ErrorActionPreference = 'Stop'
$repo = '<REPO>'
$config = '<CONFIG>'
$logDir = Join-Path $env:LOCALAPPDATA 'magnetgate'
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
Set-Location $repo
& node src/client.js $config *>> (Join-Path $logDir 'client.log')
