# Generated by install-client-windows.ps1 - do not edit manually
$ErrorActionPreference = 'Stop'
$repo = '<REPO>'
$config = '<CONFIG>'
Set-Location $repo
& node src/client.js $config *>> (Join-Path $repo 'client.log')
