package offer

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The vectors are generated by the Node implementation (scripts/dev/gen-vectors.mjs) and are the
// contract between the two: if the policy changes on either side, the file changes and this test
// fails until the Go port is updated too.

type vectorFile struct {
	Offer struct {
		Merge []struct {
			Name     string          `json:"name"`
			Prev     json.RawMessage `json:"prev"`
			Incoming json.RawMessage `json:"incoming"`
			Want     json.RawMessage `json:"want"`
		} `json:"merge"`
		Pick []struct {
			Pref []string `json:"pref"`
			DP   []struct {
				T string `json:"t"`
			} `json:"dp"`
			Want string `json:"want"`
		} `json:"pick"`
		Peers []struct {
			Known []int  `json:"known"`
			Peers []Peer `json:"peers"`
			Want  []int  `json:"want"`
		} `json:"peers"`
	} `json:"offer"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "v1.json"))
	if err != nil {
		t.Fatalf("read vectors (run `node scripts/dev/gen-vectors.mjs`): %v", err)
	}
	var v vectorFile
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Offer.Merge) == 0 || len(v.Offer.Pick) == 0 || len(v.Offer.Peers) == 0 {
		t.Fatal("the vectors carry no offer cases (regenerate them)")
	}
	return v
}

func decode(raw json.RawMessage) *Offer {
	if len(raw) == 0 || string(raw) == "null" {
		return nil
	}
	var o Offer
	if err := json.Unmarshal(raw, &o); err != nil {
		return nil
	}
	return &o
}

// sameDP compares two data-plane lists by type and by the raw JSON of each entry.
func sameDP(a, b []json.RawMessage) bool {
	if len(a) != len(b) {
		return false
	}
	index := map[string]string{}
	for _, raw := range a {
		index[TypeOf(raw)] = string(raw)
	}
	for _, raw := range b {
		if index[TypeOf(raw)] != string(raw) {
			return false
		}
	}
	return true
}

func TestMergeMatchesNodePolicy(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Offer.Merge {
		got := Merge(decode(c.Prev), decode(c.Incoming))
		want := decode(c.Want)
		switch {
		case got == nil && want == nil:
			// both refuse the incoming offer
		case got == nil || want == nil:
			t.Errorf("%s: got %v, want %v", c.Name, got != nil, want != nil)
		default:
			if got.TS != want.TS || got.V != want.V {
				t.Errorf("%s: version/timestamp %d/%d, want %d/%d", c.Name, got.V, got.TS, want.V, want.TS)
			}
			if !sameDP(got.DP, want.DP) {
				t.Errorf("%s: data planes differ\n got %s\nwant %s",
					c.Name, summarise(got.DP), summarise(want.DP))
			}
			// identity fields must survive a merge
			if got.Node != want.Node || got.Country != want.Country {
				t.Errorf("%s: identity lost (%q/%q, want %q/%q)", c.Name, got.Node, got.Country, want.Node, want.Country)
			}
			if len(got.Peers) != len(want.Peers) {
				t.Errorf("%s: peers lost (%d, want %d)", c.Name, len(got.Peers), len(want.Peers))
			}
		}
	}
}

func summarise(dp []json.RawMessage) string {
	out := ""
	for i, raw := range dp {
		if i > 0 {
			out += ", "
		}
		out += TypeOf(raw) + "=" + string(raw)
	}
	return out
}

func TestPickMatchesNodePolicy(t *testing.T) {
	v := loadVectors(t)
	for i, c := range v.Offer.Pick {
		dp := make([]json.RawMessage, 0, len(c.DP))
		for _, entry := range c.DP {
			raw, _ := json.Marshal(entry)
			dp = append(dp, raw)
		}
		candidate := Offer{DP: dp}
		got := candidate.Pick(c.Pref)
		gotType := TypeOf(got)
		if c.Want == "" {
			if got != nil {
				t.Errorf("pick case %d: got %q, want nothing", i, gotType)
			}
			continue
		}
		if gotType != c.Want {
			t.Errorf("pick case %d: got %q, want %q", i, gotType, c.Want)
		}
	}
}

func TestNewPeerSlotsMatchesNodePolicy(t *testing.T) {
	v := loadVectors(t)
	for i, c := range v.Offer.Peers {
		got := NewPeerSlots(c.Known, c.Peers, 16)
		if len(got) != len(c.Want) {
			t.Errorf("peer case %d: got %v, want %v", i, got, c.Want)
			continue
		}
		for j := range got {
			if got[j] != c.Want[j] {
				t.Errorf("peer case %d: got %v, want %v", i, got, c.Want)
				break
			}
		}
	}
}

func TestMergeBehaviourThatMatters(t *testing.T) {
	// a compact DHT offer must not clobber the hysteria2 entry that only the Nostr channel carries
	reality := json.RawMessage(`{"t":"reality","host":"203.0.113.1","port":443}`)
	hy2 := json.RawMessage(`{"t":"hy2","host":"203.0.113.1","port":443,"ca":["cert"]}`)
	prev := &Offer{V: Schema, TS: 5000, DP: []json.RawMessage{reality, hy2}}
	incoming := &Offer{V: Schema, TS: 5000, DP: []json.RawMessage{reality}}
	merged := Merge(prev, incoming)
	if merged == nil || len(merged.DP) != 2 {
		t.Fatalf("merging the same generation must keep both planes, got %v", merged)
	}
	if merged.Pick([]string{"hy2"}) == nil {
		t.Error("the hysteria2 entry must still be pickable after a merge")
	}
	if merged.Pick([]string{"reality"}) == nil {
		t.Error("the reality entry must be pickable")
	}
}

func TestSlotRangeIsValidated(t *testing.T) {
	if got := NewPeerSlots(nil, []Peer{{Slot: 0}}, 0); len(got) != 0 {
		t.Errorf("with maxSlots 0 nothing is in range, got %v", got)
	}
	if got := NewPeerSlots(nil, []Peer{{Slot: 15}}, 16); len(got) != 1 {
		t.Errorf("the last slot must be accepted, got %v", got)
	}
	if got := NewPeerSlots(nil, []Peer{{Slot: 16}}, 16); len(got) != 0 {
		t.Errorf("one past the last slot must be refused, got %v", got)
	}
}

// A hostile or malformed peers list must never be read as "slot 0": that is the silent default the
// slot rules exist to prevent, and the Node side was fixed to match this.
func TestParsePeersIsStrict(t *testing.T) {
	valid, err := ParsePeers(json.RawMessage(`[{"slot":1,"ts":10},{"slot":2,"ts":11}]`))
	if err != nil || len(valid) != 2 || valid[0].Slot != 1 || valid[1].TS != 11 {
		t.Errorf("a well formed list must parse: %v %v", valid, err)
	}

	skipped, err := ParsePeers(json.RawMessage(`[{"ts":1},{"slot":null,"ts":2},{"slot":4,"ts":3}]`))
	if err != nil {
		t.Fatalf("missing or null slots are skipped, not fatal: %v", err)
	}
	if len(skipped) != 1 || skipped[0].Slot != 4 {
		t.Errorf("only the entry with a real slot may survive, got %v", skipped)
	}

	for _, bad := range []string{`[{"slot":1.5}]`, `[{"slot":"2"}]`, `[{"slot":true}]`, `not json`} {
		if _, err := ParsePeers(json.RawMessage(bad)); err == nil {
			t.Errorf("%s must be rejected rather than partly trusted", bad)
		}
	}

	for _, empty := range []string{"", "null", "[]"} {
		got, err := ParsePeers(json.RawMessage(empty))
		if err != nil || len(got) != 0 {
			t.Errorf("%q must yield no peers and no error, got %v %v", empty, got, err)
		}
	}
}

// The rule-set manifest reaches a client only over Nostr, like the pinned hysteria2 endpoint, so the
// merge of two views of one generation has to keep it. Starting from prev silently dropped it whenever
// the DHT view arrived first, which is the ordinary order: DHT is polled, Nostr is pushed.
func TestMergeKeepsTheRuleSetManifestFromEitherView(t *testing.T) {
	withRS := &Offer{V: Schema, TS: 1000, DP: []json.RawMessage{json.RawMessage(`{"t":"mgt"}`)},
		RuleSets: &RuleSets{V: 3, Sets: []RuleSetItem{{
			Tag: "blocked-domains", URL: "https://example.test/x.srs", SHA256: strings.Repeat("a", 64), Bytes: 10,
		}}}}
	withoutRS := &Offer{V: Schema, TS: 1000, DP: []json.RawMessage{json.RawMessage(`{"t":"reality"}`)}}

	// the DHT view first, then the Nostr view: the manifest must survive
	if got := Merge(withoutRS, withRS); got.RuleSets == nil || got.RuleSets.V != 3 {
		t.Fatalf("the manifest was dropped when the plain view was merged first: %+v", got.RuleSets)
	}
	// and the other way round, where prev already has it and the incoming view does not
	if got := Merge(withRS, withoutRS); got.RuleSets == nil || got.RuleSets.V != 3 {
		t.Fatalf("the manifest was dropped when the plain view arrived second: %+v", got.RuleSets)
	}
}

func TestRuleSetManifestRejectsWhatCannotBeTrusted(t *testing.T) {
	ok := RuleSetItem{Tag: "t", URL: "https://example.test/x.srs", SHA256: strings.Repeat("a", 64), Bytes: 10}
	for name, broken := range map[string]RuleSetItem{
		"plain http":   {Tag: "t", URL: "http://example.test/x.srs", SHA256: ok.SHA256, Bytes: 10},
		"short digest": {Tag: "t", URL: ok.URL, SHA256: strings.Repeat("a", 63), Bytes: 10},
		"not hex":      {Tag: "t", URL: ok.URL, SHA256: strings.Repeat("z", 64), Bytes: 10},
		"no size":      {Tag: "t", URL: ok.URL, SHA256: ok.SHA256, Bytes: 0},
		"absurd size":  {Tag: "t", URL: ok.URL, SHA256: ok.SHA256, Bytes: MaxRuleSetBytes + 1},
		"no tag":       {Tag: "", URL: ok.URL, SHA256: ok.SHA256, Bytes: 10},
	} {
		if (&RuleSets{V: 1, Sets: []RuleSetItem{broken}}).Valid() {
			t.Errorf("%s was accepted", name)
		}
	}
	if (&RuleSets{V: 0, Sets: []RuleSetItem{ok}}).Valid() {
		t.Error("generation 0 was accepted")
	}
	if (&RuleSets{V: 1}).Valid() {
		t.Error("an empty manifest was accepted")
	}
	if !(&RuleSets{V: 1, Sets: []RuleSetItem{ok}}).Valid() {
		t.Error("a good manifest was rejected")
	}
}

// The update manifest is the only field acting on which means installing code, so what counts as a
// valid one is spelled out rather than assumed. Validity here says nothing about whether the update
// should be installed - that needs the installed version - only that the manifest describes a release
// at all.
func TestUpdateManifestValidity(t *testing.T) {
	good := Update{
		V: 1, VersionCode: 198, VersionName: "0.1.0+abc1234",
		URL:    "https://example.test/magnetgate.apk",
		SHA256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
		Bytes:  85 << 20,
	}
	if !good.Valid() {
		t.Fatal("a complete manifest must be valid")
	}
	// http is accepted deliberately: the digest is what protects this download, not the transport, and
	// the nodes serving these packages have no domain and therefore no certificate. See Update.
	overHTTP := good
	overHTTP.URL = "http://198.51.100.7:45000/x/magnetgate.apk"
	if !overHTTP.Valid() {
		t.Fatal("an http source with a pinned digest is valid; refusing it would mean no updates at all")
	}

	var missing *Update
	if missing.Valid() {
		t.Fatal("no manifest is not a valid one")
	}

	cases := map[string]func(u *Update){
		"no version code is not a release":       func(u *Update) { u.VersionCode = 0 },
		"no version name is not a release":       func(u *Update) { u.VersionName = "" },
		"a url that is neither http nor https":   func(u *Update) { u.URL = "ftp://example.test/a.apk" },
		"a relative url is not a source":         func(u *Update) { u.URL = "/a.apk" },
		"a short digest is not a digest":         func(u *Update) { u.SHA256 = "abc" },
		"a digest must be hex":                   func(u *Update) { u.SHA256 = "zz23456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" },
		"an upper-case digest is not the form":   func(u *Update) { u.SHA256 = "0123456789ABCDEF0123456789abcdef0123456789abcdef0123456789abcdef" },
		"a package of no size is not a package":  func(u *Update) { u.Bytes = 0 },
		"nor is one larger than the cap":         func(u *Update) { u.Bytes = MaxUpdateBytes + 1 },
		"a manifest without a schema is not one": func(u *Update) { u.V = 0 },
	}
	for why, break_ := range cases {
		candidate := good
		break_(&candidate)
		if candidate.Valid() {
			t.Fatalf("%s: %+v", why, candidate)
		}
	}
}

// The update manifest reaches a client over Nostr only, like the rule-set manifest and the pinned
// hysteria2 endpoint, so merging the two views of one generation has to keep it from whichever side
// carries it. Added without this rule, and the phone saw no update at all while both nodes advertised
// one: the DHT view arrives first, the merge started from it, and the field was dropped in silence.
func TestMergeKeepsTheUpdateManifestFromEitherView(t *testing.T) {
	manifest := &Update{
		V: 1, VersionCode: 199, VersionName: "0.1.0+016a5f9",
		URL:    "http://198.51.100.7:45443/token/magnetgate.apk",
		SHA256: strings.Repeat("c", 64),
		Bytes:  85373369,
	}
	withUp := &Offer{V: Schema, TS: 2000, DP: []json.RawMessage{json.RawMessage(`{"t":"mgt"}`)}, Update: manifest}
	withoutUp := &Offer{V: Schema, TS: 2000, DP: []json.RawMessage{json.RawMessage(`{"t":"reality"}`)}}

	if merged := Merge(withoutUp, withUp); merged == nil || merged.Update == nil {
		t.Fatal("the Nostr view arriving second must bring its manifest with it")
	}
	if merged := Merge(withUp, withoutUp); merged == nil || merged.Update == nil {
		t.Fatal("and arriving first it must not be dropped by the DHT view")
	}
	// A newer generation replaces what came before, manifest and all.
	newer := &Offer{V: Schema, TS: 3000, DP: []json.RawMessage{json.RawMessage(`{"t":"mgt"}`)}}
	if merged := Merge(withUp, newer); merged == nil || merged.Update != nil {
		t.Fatal("a newer generation without a manifest means there is no manifest any more")
	}
}
