package offer

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The vectors are generated by the Node implementation (scripts/dev/gen-vectors.mjs) and are the
// contract between the two: if the policy changes on either side, the file changes and this test
// fails until the Go port is updated too.

type vectorFile struct {
	Offer struct {
		Merge []struct {
			Name     string          `json:"name"`
			Prev     json.RawMessage `json:"prev"`
			Incoming json.RawMessage `json:"incoming"`
			Want     json.RawMessage `json:"want"`
		} `json:"merge"`
		Pick []struct {
			Pref []string `json:"pref"`
			DP   []struct {
				T string `json:"t"`
			} `json:"dp"`
			Want string `json:"want"`
		} `json:"pick"`
		Peers []struct {
			Known []int  `json:"known"`
			Peers []Peer `json:"peers"`
			Want  []int  `json:"want"`
		} `json:"peers"`
	} `json:"offer"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "v1.json"))
	if err != nil {
		t.Fatalf("read vectors (run `node scripts/dev/gen-vectors.mjs`): %v", err)
	}
	var v vectorFile
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Offer.Merge) == 0 || len(v.Offer.Pick) == 0 || len(v.Offer.Peers) == 0 {
		t.Fatal("the vectors carry no offer cases (regenerate them)")
	}
	return v
}

func decode(raw json.RawMessage) *Offer {
	if len(raw) == 0 || string(raw) == "null" {
		return nil
	}
	var o Offer
	if err := json.Unmarshal(raw, &o); err != nil {
		return nil
	}
	return &o
}

// sameDP compares two data-plane lists by type and by the raw JSON of each entry.
func sameDP(a, b []json.RawMessage) bool {
	if len(a) != len(b) {
		return false
	}
	index := map[string]string{}
	for _, raw := range a {
		index[TypeOf(raw)] = string(raw)
	}
	for _, raw := range b {
		if index[TypeOf(raw)] != string(raw) {
			return false
		}
	}
	return true
}

func TestMergeMatchesNodePolicy(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Offer.Merge {
		got := Merge(decode(c.Prev), decode(c.Incoming))
		want := decode(c.Want)
		switch {
		case got == nil && want == nil:
			// both refuse the incoming offer
		case got == nil || want == nil:
			t.Errorf("%s: got %v, want %v", c.Name, got != nil, want != nil)
		default:
			if got.TS != want.TS || got.V != want.V {
				t.Errorf("%s: version/timestamp %d/%d, want %d/%d", c.Name, got.V, got.TS, want.V, want.TS)
			}
			if !sameDP(got.DP, want.DP) {
				t.Errorf("%s: data planes differ\n got %s\nwant %s",
					c.Name, summarise(got.DP), summarise(want.DP))
			}
			// identity fields must survive a merge
			if got.Node != want.Node || got.Country != want.Country {
				t.Errorf("%s: identity lost (%q/%q, want %q/%q)", c.Name, got.Node, got.Country, want.Node, want.Country)
			}
			if len(got.Peers) != len(want.Peers) {
				t.Errorf("%s: peers lost (%d, want %d)", c.Name, len(got.Peers), len(want.Peers))
			}
		}
	}
}

func summarise(dp []json.RawMessage) string {
	out := ""
	for i, raw := range dp {
		if i > 0 {
			out += ", "
		}
		out += TypeOf(raw) + "=" + string(raw)
	}
	return out
}

func TestPickMatchesNodePolicy(t *testing.T) {
	v := loadVectors(t)
	for i, c := range v.Offer.Pick {
		dp := make([]json.RawMessage, 0, len(c.DP))
		for _, entry := range c.DP {
			raw, _ := json.Marshal(entry)
			dp = append(dp, raw)
		}
		candidate := Offer{DP: dp}
		got := candidate.Pick(c.Pref)
		gotType := TypeOf(got)
		if c.Want == "" {
			if got != nil {
				t.Errorf("pick case %d: got %q, want nothing", i, gotType)
			}
			continue
		}
		if gotType != c.Want {
			t.Errorf("pick case %d: got %q, want %q", i, gotType, c.Want)
		}
	}
}

func TestNewPeerSlotsMatchesNodePolicy(t *testing.T) {
	v := loadVectors(t)
	for i, c := range v.Offer.Peers {
		got := NewPeerSlots(c.Known, c.Peers, 16)
		if len(got) != len(c.Want) {
			t.Errorf("peer case %d: got %v, want %v", i, got, c.Want)
			continue
		}
		for j := range got {
			if got[j] != c.Want[j] {
				t.Errorf("peer case %d: got %v, want %v", i, got, c.Want)
				break
			}
		}
	}
}

func TestMergeBehaviourThatMatters(t *testing.T) {
	// a compact DHT offer must not clobber the hysteria2 entry that only the Nostr channel carries
	reality := json.RawMessage(`{"t":"reality","host":"203.0.113.1","port":443}`)
	hy2 := json.RawMessage(`{"t":"hy2","host":"203.0.113.1","port":443,"ca":["cert"]}`)
	prev := &Offer{V: Schema, TS: 5000, DP: []json.RawMessage{reality, hy2}}
	incoming := &Offer{V: Schema, TS: 5000, DP: []json.RawMessage{reality}}
	merged := Merge(prev, incoming)
	if merged == nil || len(merged.DP) != 2 {
		t.Fatalf("merging the same generation must keep both planes, got %v", merged)
	}
	if merged.Pick([]string{"hy2"}) == nil {
		t.Error("the hysteria2 entry must still be pickable after a merge")
	}
	if merged.Pick([]string{"reality"}) == nil {
		t.Error("the reality entry must be pickable")
	}
}

func TestSlotRangeIsValidated(t *testing.T) {
	if got := NewPeerSlots(nil, []Peer{{Slot: 0}}, 0); len(got) != 0 {
		t.Errorf("with maxSlots 0 nothing is in range, got %v", got)
	}
	if got := NewPeerSlots(nil, []Peer{{Slot: 15}}, 16); len(got) != 1 {
		t.Errorf("the last slot must be accepted, got %v", got)
	}
	if got := NewPeerSlots(nil, []Peer{{Slot: 16}}, 16); len(got) != 0 {
		t.Errorf("one past the last slot must be refused, got %v", got)
	}
}

// A hostile or malformed peers list must never be read as "slot 0": that is the silent default the
// slot rules exist to prevent, and the Node side was fixed to match this.
func TestParsePeersIsStrict(t *testing.T) {
	valid, err := ParsePeers(json.RawMessage(`[{"slot":1,"ts":10},{"slot":2,"ts":11}]`))
	if err != nil || len(valid) != 2 || valid[0].Slot != 1 || valid[1].TS != 11 {
		t.Errorf("a well formed list must parse: %v %v", valid, err)
	}

	skipped, err := ParsePeers(json.RawMessage(`[{"ts":1},{"slot":null,"ts":2},{"slot":4,"ts":3}]`))
	if err != nil {
		t.Fatalf("missing or null slots are skipped, not fatal: %v", err)
	}
	if len(skipped) != 1 || skipped[0].Slot != 4 {
		t.Errorf("only the entry with a real slot may survive, got %v", skipped)
	}

	for _, bad := range []string{`[{"slot":1.5}]`, `[{"slot":"2"}]`, `[{"slot":true}]`, `not json`} {
		if _, err := ParsePeers(json.RawMessage(bad)); err == nil {
			t.Errorf("%s must be rejected rather than partly trusted", bad)
		}
	}

	for _, empty := range []string{"", "null", "[]"} {
		got, err := ParsePeers(json.RawMessage(empty))
		if err != nil || len(got) != 0 {
			t.Errorf("%q must yield no peers and no error, got %v %v", empty, got, err)
		}
	}
}
