import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  deriveKeys,
  saltOf,
  slotSalt,
  slotBoxKey,
  targetOf,
  frame2,
  FRAME,
  OFFER_SCHEMA,
  MAX_SLOTS
} from '../../src/common.mjs'

// Deterministic cross-implementation vectors for the Android core (app-android/core).
//
// Only facts that do not depend on randomness belong in the tracked file: keys, salts, targets and the
// protocol constants. Envelope interop is random-nonce by design, so it is checked at run time in both
// directions by scripts/dev/verify-vectors.mjs (Node seals → Go unseals, Go seals → Node unseals).
//
//   node scripts/dev/gen-vectors.mjs            # write app-android/core/proto/testdata/v1.json
//   node scripts/dev/gen-vectors.mjs --print    # print instead of writing (diff the result)
export const TEST_PSK = 'vector-test-psk-not-a-secret-0123456789abcdef'
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
export const vectorsFile = path.join(root, 'app-android', 'core', 'proto', 'testdata', 'v1.json')

const hex = (buf) => Buffer.from(buf).toString('hex')
// length prefix (4) + nonce (24) + MAC (16) + version/sequence/type/streamId (14)
const FRAME_HDR_JS = 4 + 24 + 16 + 14

export function buildVectors(psk = TEST_PSK) {
  const { pk, boxKey } = deriveKeys(psk)
  const slots = []
  for (let slot = 0; slot < 4; slot++) {
    const salt = slotSalt(psk, slot)
    slots.push({
      slot,
      salt: hex(salt),
      target: hex(targetOf(pk, salt)),
      boxKey: hex(slotBoxKey(psk, slot))
    })
  }

  // Frame wire lengths are deterministic for a given payload size (only the nonce and the pad bytes are
  // random), which makes them a solid cross-implementation check on the framing layer: same buckets,
  // same header, same limit.
  const frameLengths = []
  for (const plainLen of [0, 1, 62, 63, 254, 255, 4094, 4095, 10000]) {
    const plain = Buffer.alloc(plainLen, 7)
    frameLengths.push({
      plainLen,
      data: frame2(boxKey, FRAME.DATA, 1, plain, 0n).length,
      open: frame2(boxKey, FRAME.OPEN, 1, plain, 0n).length
    })
  }
  return {
    comment: [
      'Deterministic protocol vectors shared by the Node client and the Android Go core.',
      'Generated by scripts/dev/gen-vectors.mjs from src/common.mjs; checked by',
      'app-android/core/proto/*_test.go and by scripts/dev/verify-vectors.mjs.',
      'The PSK is a test value and is not a secret.'
    ],
    psk,
    constants: {
      envelopeVersion: 4,
      offerSchema: OFFER_SCHEMA,
      maxSlots: MAX_SLOTS,
      maxSealDomain: 64,
      frameHeaderSize: FRAME_HDR_JS,
      maxFrameBytes: 4 * 1024 * 1024,
      minFrameLength: 54
    },
    keys: { pk: hex(pk), boxKey: hex(boxKey), salt0: hex(saltOf(psk)) },
    slots,
    frameLengths
  }
}

const serialise = (vectors) => JSON.stringify(vectors, null, 2) + '\n'

export function writeVectors(file = vectorsFile) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, serialise(buildVectors()))
  return file
}

// Used by verify-vectors.mjs: regenerate only when the tracked file is missing or stale, so a KDF change
// shows up as a diff instead of being silently overwritten.
export function genVectorsIfStale(file = vectorsFile) {
  const wanted = serialise(buildVectors())
  let current = null
  try {
    current = fs.readFileSync(file, 'utf8')
  } catch {}
  if (current === wanted) return { file, changed: false }
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, wanted)
  return { file, changed: true }
}

const isMain =
  process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))

if (isMain) {
  if (process.argv.includes('--print')) {
    process.stdout.write(serialise(buildVectors()))
  } else {
    const file = writeVectors()
    console.log(`vectors written: ${path.relative(root, file)} (${buildVectors().slots.length} slots)`)
  }
}
