import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, ArrowRight, ArrowDown, Check, Copy, DownloadSimple, ShieldCheck, GlobeHemisphereWest, Power, WindowsLogo, AndroidLogo, AppleLogo, GithubLogo, Plus, Minus, LockKey, PhoneCall, Play, Code, SlidersHorizontal, X, CircleNotch } from '@phosphor-icons/react'
import { motion, useReducedMotion } from 'motion/react'
import './styles.css'

const repository = 'https://github.com/danifest751/magnetgate'
const Icon = ({ component: Component, size = 21, ...props }) => <Component size={size} weight="regular" aria-hidden="true" {...props}/>
function Brand({ light = false }) { return <a href="#" className={`brand ${light ? 'brand-light' : ''}`} aria-label="MagnetGate — в начало"><img src="/mark.svg" width="37" height="37" alt=""/>magnet<span>gate</span></a> }
function Reveal({ children, className = '', delay = 0 }) {
  const reduced = useReducedMotion()
  return <motion.div initial={reduced ? false : { opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .65, delay }} className={className}>{children}</motion.div>
}

function AppPreview() {
  const [mode, setMode] = useState('full')
  return <div className="app-window" aria-label="Интерактивная иллюстрация приложения, без настоящего подключения">
    <div className="app-title"><span className="window-dots"><i/><i/><i/></span><span>MagnetGate</span><span className="demo-label">МАКЕТ ИНТЕРФЕЙСА</span></div>
    <div className="app-body"><aside><img src="/mark.svg" width="34" height="34" alt=""/><span className="app-nav-active"><Icon component={Power}/>Подключение</span><span><Icon component={GlobeHemisphereWest}/>Сайты</span><span><Icon component={SlidersHorizontal}/>Настройки</span><small>Личный доступ<br/>Ваше устройство</small></aside>
    <div className="app-main"><div className="flex justify-between items-center"><span className="mono text-[10px] tracking-widest">ВАШЕ СОЕДИНЕНИЕ</span><span className="tiny-badge">Личный доступ</span></div><div className="power-circle"><Icon component={Power} size={38}/></div><h3>Всё начинается<br/>с одного подключения.</h3><p>Сайты, видео и звонки — в одном приложении.</p><div className="app-mode"><button onClick={() => setMode('full')} aria-pressed={mode === 'full'}>Весь интернет</button><button onClick={() => setMode('split')} aria-pressed={mode === 'split'}>Только выбранное</button></div><div className="app-location"><Icon component={GlobeHemisphereWest}/><span>Страна выхода<strong>Автоматически</strong></span><ArrowRight size={17}/></div><div className="app-help">{mode === 'full' ? 'Весь трафик через VPN, кроме ваших исключений.' : 'Вы выбираете сайты, которые пойдут через VPN.'}</div></div></div>
  </div>
}

function Access({ info }) {
  const [stage, setStage] = useState('idle')
  const [challenge, setChallenge] = useState('')
  const [code, setCode] = useState('')
  const [expires, setExpires] = useState(0)
  const [message, setMessage] = useState('')
  const [copied, setCopied] = useState(false)
  const widget = useRef(null), widgetId = useRef(null)
  useEffect(() => {
    if (stage !== 'challenge' || !info?.sitekey) return
    let alive = true
    const render = () => {
      if (!alive || !widget.current || !window.turnstile) return
      widgetId.current = window.turnstile.render(widget.current, { sitekey: info.sitekey, action: 'access', theme: 'light', language: 'ru', callback: token => setChallenge(token), 'expired-callback': () => setChallenge(''), 'error-callback': () => { setChallenge(''); setMessage('Проверка не загрузилась. Проверьте соединение и попробуйте снова.') } })
    }
    let script = document.getElementById('turnstile-script')
    if (window.turnstile) render()
    else {
      if (!script) { script = document.createElement('script'); script.id = 'turnstile-script'; script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'; script.async = true; document.head.append(script) }
      script.addEventListener('load', render)
    }
    return () => { alive = false; script?.removeEventListener('load', render); if (widgetId.current !== null) { window.turnstile?.remove(widgetId.current); widgetId.current = null } }
  }, [stage, info?.sitekey])
  async function issue() {
    setStage('loading'); setMessage('')
    try {
      const reply = await fetch('/api/access', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ challenge }), signal: AbortSignal.timeout(20000) })
      const data = await reply.json()
      if (!reply.ok) throw new Error(data.error || 'Не удалось получить код.')
      setCode(data.code); setExpires(data.expires); setStage('ready')
    } catch (error) { setMessage(error.name === 'TimeoutError' ? 'Сервис не ответил вовремя. Попробуйте снова.' : error.message); setChallenge(''); setStage('challenge') }
  }
  async function copy() { try { await navigator.clipboard.writeText(code); setCopied(true) } catch { setMessage('Выделите код в поле и скопируйте его вручную.') } }
  function save() {
    const blob = new Blob([`Личный код MagnetGate\n${code}\n\nВставьте его в приложении: Настройки → Личный доступ.\nНикому не пересылайте этот файл.\nДействует до ${new Date(expires * 1000).toLocaleDateString('ru-RU')}.\nhttps://magnet.norma.so\n`], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = 'magnetgate-access.txt'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  return <div id="access" className="access-box scroll-mt-28"><div className="flex justify-between items-start gap-4"><span className="eyebrow">ВАШ ЛИЧНЫЙ ПРОПУСК</span><LockKey size={24}/></div><h3>{stage === 'ready' ? 'Добро пожаловать.' : 'Интернет ближе,\nчем кажется.'}</h3><p>{stage === 'ready' ? 'Код готов. Сохраните его и добавьте в приложение на своих устройствах.' : 'Получите бесплатный код. Без почты, банковской карты и ожидания ответа администратора.'}</p>
    {stage === 'idle' && <><button className="button button-dark w-full" onClick={() => { setStage('challenge'); setMessage('') }} disabled={!info?.sitekey || !info.available}>Получить личный код<ArrowUpRight size={21}/></button><span className="access-note">{!info ? 'Проверяем доступность сервиса…' : info.available ? 'Бесплатно · до 2 устройств · на 30 дней' : 'Ноды заняты или временно недоступны. Попробуйте позже.'}</span></>}
    {stage === 'challenge' && <><div ref={widget} className="challenge-widget"/><button className="button button-dark w-full" disabled={!challenge} onClick={issue}>Получить код<ArrowRight size={20}/></button><p className="privacy-note">Проверка Cloudflare Turnstile защищает от массовой выдачи кодов. При её запуске браузер обращается к Cloudflare.</p></>}
    {stage === 'loading' && <div className="access-loading" role="status"><div/><div/><p>Создаём ваш личный доступ…</p></div>}
    {stage === 'ready' && <><label className="code-label" htmlFor="access-code">Ваш код — сохраните его</label><textarea id="access-code" readOnly value={code} onFocus={event => event.target.select()} rows={3}/><div className="grid grid-cols-2 gap-3 mt-3"><button className="button button-dark" onClick={copy}>{copied ? <Check size={18}/> : <Copy size={18}/>} {copied ? 'Скопировано' : 'Копировать'}</button><button className="button button-line" onClick={save}><DownloadSimple size={18}/>Сохранить</button></div><p className="privacy-note">Действует до {new Date(expires * 1000).toLocaleDateString('ru-RU')}. Код даёт доступ к вашим двум устройствам — не публикуйте его.</p><a className="text-link" href="#guide">Как добавить код в приложение<ArrowRight size={18}/></a></>}
    {message && <p className="error-message" role="alert">{message}</p>}
  </div>
}

const guides = {
  mac: [{ title: 'Выберите сборку для своего Mac', text: 'В меню Apple откройте «Об этом Mac». Если указан чип Apple M — выберите Apple Silicon. Если указан процессор Intel — скачайте версию Intel. Откройте DMG и перенесите MagnetGate в «Программы».' }, { title: 'Добавьте личный код', text: 'Откройте приложение, затем «Настройки» → «Личный доступ MagnetGate». Вставьте код с сайта и нажмите «Подключить личный доступ». Это тот же код, что используется на Windows и Android: всего можно активировать два устройства.' }, { title: 'Подключитесь и разрешите настройку сети', text: 'На экране «Подключение» выберите «Личный доступ MagnetGate» и нажмите «Подключить». macOS запросит пароль администратора для настройки VPN. Дождитесь проверки соединения. Сборки пока без нотариализации Apple; разрешайте запуск только после проверки источника загрузки.' }],
  windows: [{ title: 'Скачайте и распакуйте приложение', text: 'Загрузите ZIP для Windows. Извлеките всю папку из архива и запустите magnetgate.exe. Для создания VPN-интерфейса понадобятся права администратора.' }, { title: 'Добавьте личный код', text: 'Откройте «Настройки». В блоке «Личный доступ MagnetGate» вставьте код с этой страницы и нажмите «Подключить личный доступ».' }, { title: 'Нажмите «Подключить»', text: 'Вернитесь в «Подключение». Оставьте страну «Автоматически» и режим «Весь интернет». Дождитесь проверки соединения — после этого откройте нужный сайт или приложение.' }],
  android: [{ title: 'Установите приложение на телефон', text: 'Скачайте APK для Android. Откройте файл и разрешите установку из вашего браузера, если система спросит. После установки это разрешение можно выключить.' }, { title: 'Вставьте код в настройках', text: 'В приложении откройте «Настройки» → «Доступ». В блоке «Личный доступ MagnetGate» вставьте код и нажмите «Подключить личный доступ».' }, { title: 'Разрешите VPN-подключение', text: 'Вернитесь на экран «Связь» и нажмите «Подключить». Подтвердите системный запрос Android. Приложение само проверит, что интернет доступен через ноду.' }]
}
const questions = [
  ['Это действительно бесплатно?', 'Да. MagnetGate — независимый проект с открытым исходным кодом. За публичный доступ платить не нужно. Мощность серверов ограничена, поэтому действуют условия справедливого использования.'],
  ['Будут работать звонки и видеосвязь?', 'Публичное подключение передаёт TCP и UDP: это нужно сайтам, видео, голосовым и видеозвонкам. Отдельного запрета звонков нет. Качество зависит от вашей сети, загрузки нод и самого мессенджера.'],
  ['Сколько устройств можно подключить?', 'Один личный код можно активировать на двух устройствах. Например, на компьютере и телефоне. Каждое устройство получает собственные данные подключения. Код действует 30 дней.'],
  ['Какие ограничения есть?', 'До 5 ГиБ трафика в сутки на один код, до 20 Мбит/с на подключение. Суточный общий резерв — 100 ГиБ. Число одновременных подключений и новых кодов ограничено, чтобы сервис оставался доступным. Счётчики суток обновляются в 00:00 UTC. Это верхние пределы, а не гарантия скорости.'],
  ['Подключение не работает. Что проверить?', 'Убедитесь, что обычный интернет работает, выключите другой VPN и попробуйте страну «Автоматически». Затем откройте диагностику приложения. Текущий публичный транспорт использует UDP: если оператор полностью блокирует UDP, эта версия подключения не заработает. Попробуйте другую сеть.'],
  ['Что хранится на сервере?', 'Для доступа и ограничений хранятся хеш кода, идентификаторы устройств, срок доступа и счётчики трафика. Для ограничения выдачи используется суточный хеш подсети; он удаляется при следующей выдаче после смены суток. Журнал посещённых сайтов для этой системы не ведётся. HTTPS-содержимое сервис не расшифровывает.'],
  ['Можно ли использовать на iPhone или Mac?', 'Для Mac предусмотрены две сборки: Apple Silicon (чипы Apple M) и Intel. Личный код работает так же, как на Windows и Android. macOS-сборки экспериментальные, без нотариализации Apple; установка и подключение на пользовательском Mac ещё требуют полевой проверки. Приложения для iOS сейчас нет.'],
  ['Что делать, если личный код попал к другому человеку?', 'Отзовите его в форме ниже. Доступ связанных устройств будет закрыт после ближайшей проверки сервера, обычно в течение нескольких секунд. Затем получите новый код, когда лимит выдачи это позволит.']
]

function Revoke() {
  const [code, setCode] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  return <details className="revoke"><summary>Отозвать потерянный или раскрытый код</summary><form onSubmit={async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const response = await fetch('/api/revoke', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: code.trim() }), signal: AbortSignal.timeout(15000) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setCode(''); setMessage('Код отозван. Связанные устройства потеряют доступ.') } catch (error) { setMessage(error.message || 'Не удалось отозвать код.') } finally { setBusy(false) } }}><label htmlFor="revoke-code">Код, доступ по которому нужно закрыть</label><input id="revoke-code" type="password" value={code} onChange={event => setCode(event.target.value)} placeholder="MG1-…" maxLength={68} required autoComplete="off"/><p>Это отключит оба связанных устройства. Действие нельзя отменить.</p><button className="button button-dark" disabled={busy || !/^MG1-[a-f0-9]{64}$/.test(code.trim())}>{busy ? 'Отзываем…' : 'Отозвать доступ'}</button><p role="status">{message}</p></form></details>
}

function App() {
  const [info, setInfo] = useState(null), [infoError, setInfoError] = useState(false), [platform, setPlatform] = useState('windows'), [menu, setMenu] = useState(false)
  async function refreshInfo() { try { const response = await fetch('/api/info', { signal: AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(); setInfo(await response.json()); setInfoError(false) } catch { setInfoError(true) } }
  useEffect(() => { refreshInfo(); const timer = setInterval(refreshInfo, 30000); return () => clearInterval(timer) }, [])
  return <><header className="header"><div className="shell header-inner"><Brand/><nav className={menu ? 'nav nav-open' : 'nav'} aria-label="Главная навигация"><a href="#about" onClick={() => setMenu(false)}>О проекте</a><a href="#guide" onClick={() => setMenu(false)}>Как подключиться</a><a href="#questions" onClick={() => setMenu(false)}>Вопросы</a></nav><a className="header-github" href={repository} target="_blank" rel="noreferrer"><GithubLogo size={20}/>Исходный код<ArrowUpRight size={15}/></a><button className="menu-button" aria-label={menu ? 'Закрыть меню' : 'Открыть меню'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X size={25}/> : <SlidersHorizontal size={25}/>}</button></div></header>
  <main><section className="hero shell"><Reveal className="hero-copy"><div className="eyebrow"><span className="status-dot"/>БЕСПЛАТНЫЙ ПРОЕКТ · ОТКРЫТЫЙ КОД</div><h1>Ваш интернет.<br/><span>Ваша связь.</span></h1><p className="hero-description">Будьте рядом, даже когда далеко.<br/>MagnetGate подключает к готовым VPN-нодам — для привычных сайтов, видео и звонков.</p><div className="hero-actions"><a className="button button-dark" href="#start">Начать бесплатно<ArrowUpRight size={22}/></a><a className="text-link" href="#guide">Как это работает<ArrowDown size={18}/></a></div><div className="hero-platforms"><WindowsLogo size={20}/><span>Windows</span><i/><AndroidLogo size={21}/><span>Android</span><i/><AppleLogo size={20}/><span>macOS</span><span className="beta-label">ОТКРЫТАЯ БЕТА</span></div></Reveal><Reveal className="hero-art" delay={.15}><img className="gateway-image" src="/images/gateway.webp" width="1254" height="1254" alt="Магнитные арки MagnetGate, соединённые зелёной лентой" fetchPriority="high"/><div className="hero-floating"><span className="connection-line"/><div><strong>Соединение имеет значение.</strong><span>Технология внутри. Простота снаружи.</span></div><ArrowUpRight size={20}/></div><span className="art-caption mono">MAGNETGATE / CONNECT FREELY</span></Reveal></section>
  <section className="manifest-strip"><div className="shell grid grid-cols-2 md:grid-cols-4 gap-6"><span><Check size={19}/>Без подписки и оплаты</span><span><LockKey size={19}/>Собственный код доступа</span><span><PhoneCall size={19}/>TCP и UDP для звонков</span><span><Code size={19}/>Открытый исходный код</span></div></section>
  <section id="about" className="section shell scroll-mt-20"><Reveal className="section-heading"><div className="eyebrow">01 / ПРОСТО БЫТЬ НА СВЯЗИ</div><div><h2>Меньше настроек.<br/>Больше обычной жизни.</h2><p>Не нужно поднимать сервер, искать ключи в чатах или разбираться в протоколах. Получите личный доступ и используйте знакомые приложения.</p></div></Reveal><div className="feature-layout"><Reveal className="preview-stage"><AppPreview/><div className="preview-caption"><span>Управление соединением в одном окне</span><span>Попробуйте переключить режимы ↑</span></div></Reveal><div className="feature-text"><Reveal><span className="feature-number">01</span><h3>Открывайте нужное.</h3><p>Работа, обучение, видео и повседневные сайты. Весь интернет через VPN или только выбранные вами адреса.</p></Reveal><Reveal delay={.1}><span className="feature-number">02</span><h3>Слышите друг друга.</h3><p>Голос и видеосвязь тоже важны. Подключение поддерживает UDP — без отдельного запрета звонков.</p></Reveal><Reveal delay={.2}><span className="feature-number">03</span><h3>Сохраняйте контроль.</h3><p>Ваш код, ваши устройства. Если код потерян или раскрыт, его можно отозвать прямо здесь.</p></Reveal></div></div></section>
  <section id="start" className="start-section scroll-mt-20"><div className="shell start-grid"><Reveal className="start-copy"><div className="eyebrow">02 / ОТКРОЙТЕ СВОЙ MAGNETGATE</div><h2>Одно приложение.<br/>Один личный код.<br/><span>И вы на связи.</span></h2><p>Начните с версии для своего устройства.<br/>Затем получите код в соседнем блоке.</p><div className="download-list">{[['windows', WindowsLogo, 'Для Windows', 'ZIP · распакуйте и запустите'], ['android', AndroidLogo, 'Для Android', 'APK · Android 8 и новее · ARM64'], ['macArm', AppleLogo, 'Для Mac · Apple Silicon', 'DMG · чипы Apple M1 и новее'], ['macIntel', AppleLogo, 'Для Mac · Intel', 'DMG · процессоры Intel']].map(([key, Component, title, description]) => <div className="download-row" key={key}><Component size={28}/><div><strong>{title}</strong><span>{description}</span></div>{info?.downloads?.[key]?.url ? <a href={info.downloads[key].url} className="download-action" aria-label={'Скачать приложение ' + title}><DownloadSimple size={23}/></a> : <span className="download-pending">{infoError ? 'Нет связи' : 'Сборка готовится'}</span>}</div>)}</div><p className="download-note">Какой Mac выбрать: меню Apple → «Об этом Mac» → строка «Чип» или «Процессор». Mac-сборки экспериментальные, без нотариализации Apple.</p><p className="download-note">Скачивайте только с этой страницы или из репозитория проекта. Публичные сборки не содержат общего ключа владельца нод.</p>{infoError && <button onClick={refreshInfo} className="text-link">Не удалось проверить сервис. Повторить<ArrowRight size={18}/></button>}<a className="text-link" href={repository} target="_blank" rel="noreferrer">Другие платформы и исходники<ArrowUpRight size={17}/></a></Reveal><Reveal delay={.1}><Access info={info}/></Reveal></div></section>
  <section id="guide" className="section shell scroll-mt-20"><Reveal className="section-heading"><div className="eyebrow">03 / ОТ СКАЧИВАНИЯ ДО ПОДКЛЮЧЕНИЯ</div><div><h2>Первый раз?<br/>Пройдём вместе.</h2><p>Всё, что нужно для старта, — ниже. Настройка занимает несколько простых шагов.</p></div></Reveal><div className="guide-layout"><div className="guide-tabs" role="tablist" aria-label="Инструкция для вашей системы">{[['windows', WindowsLogo, 'Windows'], ['android', AndroidLogo, 'Android'], ['mac', AppleLogo, 'macOS']].map(([key, Component, title]) => <button key={key} role="tab" id={'tab-' + key} aria-controls="guide-panel" aria-selected={platform === key} onClick={() => setPlatform(key)}><Component size={24}/>{title}<ArrowUpRight size={18}/></button>)}<div className="guide-tip"><ShieldCheck size={30}/><p>Личный код — как ключ от двери. Храните его у себя и не пересылайте в общие чаты.</p></div></div><div id="guide-panel" role="tabpanel" aria-labelledby={'tab-' + platform} className="steps">{guides[platform].map((step, index) => <Reveal key={platform + index} delay={index * .06} className="step"><span className="step-number">0{index + 1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div><Check size={20}/></Reveal>)}<div className="guide-finish"><span className="status-dot"/><span>Готово. Чтобы завершить сеанс, нажмите «Отключить».</span></div></div></div></section>
  <section className="trust-section"><div className="shell trust-grid"><Reveal><div className="eyebrow">04 / ОБЩИЙ РЕСУРС. ЛИЧНЫЙ ДОСТУП.</div><h2>Бесплатно.<br/>Прозрачно.<br/><span>По-человечески.</span></h2><p>За проектом стоят реальные серверы и люди. Мы делимся их ресурсом и вводим понятные пределы, чтобы места хватало всем.</p><a className="button button-light" href={repository} target="_blank" rel="noreferrer"><GithubLogo size={21}/>Посмотреть код<ArrowUpRight size={18}/></a></Reveal><Reveal className="trust-data"><div><span className="big-data">0 ₽</span><p>за публичный доступ<br/>без платёжной карты</p></div><div><span className="big-data">2</span><p>устройства<br/>на один личный код</p></div><div><span className="big-data">5 <small>ГиБ</small></span><p>трафика в сутки<br/>на ваши устройства вместе</p></div><div><span className="big-data">30 <small>дней</small></span><p>срок действия кода<br/>с момента получения</p></div><div className="trust-foot"><ShieldCheck size={22}/><p>Данные владельца нод остаются на сервере. У каждого пользователя — собственный доступ.</p></div></Reveal></div></section>
  <section className="section shell scroll-mt-20" id="questions"><Reveal className="section-heading"><div className="eyebrow">05 / ПО ДЕЛУ</div><div><h2>Вопросы?<br/>Здесь ответы.</h2><p>Возможности, ограничения и то, что полезно знать до первого подключения.</p></div></Reveal><div className="faq-list">{questions.map(([question, answer], index) => <details key={question}><summary><span className="mono faq-number">0{index + 1}</span><span>{question}</span><Plus className="faq-plus" size={21}/><Minus className="faq-minus" size={21}/></summary><p>{answer}</p></details>)}<Revoke/></div></section>
  <section className="closing shell"><div><span className="eyebrow">СВЯЗЬ НАЧИНАЕТСЯ С ВАС</span><h2>До встречи<br/>по ту сторону.</h2><a className="button button-dark" href="#start">Подключиться бесплатно<ArrowUpRight size={22}/></a></div><div className="closing-mark" aria-hidden="true"><span/><span/></div></section>
  </main><footer className="shell footer"><Brand/><p>Независимый бесплатный проект.<br/>Открытый код. Открытая бета.</p><a href={repository} target="_blank" rel="noreferrer">GitHub<ArrowUpRight size={16}/></a><a href="#questions">Условия и приватность</a><span className="mono">© {new Date().getFullYear()} MAGNETGATE</span></footer></>
}
createRoot(document.getElementById('root')).render(<App/> )
